### ISSUE TITLE
Orchestration TODO

### ISSUE THREAD

**Issue by joskuijpers** [codefeedr/codefeedr#96]
Script to:
- Run
- List what is running
- Stop running
- Run not-running
- Restart stages

Add to Codefeedr:
- [x] groupId parameter for overriding
- [x] setting groupId based on stage
- [x] listing of all stages

**Comment by joskuijpers** [comment]
Everything in here is done
